=== isabella232/sourceforge-archive/Jetty/etc/jetty.dtd
<?xml version="1.0" encoding="ISO8859_1"?>

<!ENTITY % VALUE "(#PCDATA|SystemProperty)*">

<!ELEMENT Server (Listener+,Context+)>

<!ELEMENT Listener 
(Parameter*,Init*)>
<!ATTLIST Listener
    class  NMTOKEN "com.mortbay.HTTP.HttpListener"
    interface NMTOKEN "0.0.0.0"
    port NMTOKEN "80"
>

<!ELEMENT Context (VirtualHost*,Path+,ResourceBase?,ClassPath*,Handler*)>
<!ATTLIST Context
    type (handler|application|other) "handler" 
    class NMTOKEN ""
>

<!ELEMENT Path %VALUE; >
<!ELEMENT VirtualHost %VALUE; >
<!ELEMENT ClassPath %VALUE; >
<!ELEMENT ResourceBase %VALUE; >

<!ELEMENT Application  (Parameter*,Init*)>

<!ELEMENT Handler (Parameter*,Init*)>
<!ATTLIST Handler
    class  NMTOKEN
"com.mortbay.HTTP.Handler.Servlet.ServletHandler"
>

<!ELEMENT Parameter %VALUE; >
<!ATTLIST Parameter
   name NMTOKEN #REQUIRED>

<!ELEMENT Init (Arg*)>
<!ATTLIST Init
   method NMTOKEN "init">

<!ELEMENT Arg %VALUE; >
<!ATTLIST Arg
    type (String|int|boolean) "String">

<!ELEMENT SystemProperty EMPTY>
<!ATTLIST SystemProperty
    name NMTOKEN #REQUIRED
    default NMTOKEN #IMPLIED>

=== isabella232/sourceforge-archive/Jetty/etc/jetty.xml
<?xml version="1.0"  encoding="ISO8859_1"?> 
<!DOCTYPE Server SYSTEM "jetty.dtd"> 

<Server>
  <Listener port="8080"/>
  <Listener class="com.mortbay.HTTP.JsseListener" port="8181">
    <Parameter name="Password">Secret</Parameter>
  </Listener>

  <Context type="application">
    <Path>/</Path>
    <ResourceBase><SystemProperty name="user.dir"/>/webapps/jetty/</ResourceBase>
  </Context>

  <Context>
    <Path>/handler/*</Path>
    <ResourceBase>./FileBase/</ResourceBase>
    <Handler class="com.mortbay.HTTP.Handler.Servlet.ServletHandler">
      <Init method="addServlet">
        <Arg>/dump,/dump/*</Arg>
        <Arg>com.mortbay.Servlet.Dump</Arg>
      </Init>
      <Init method="addServlet">
        <Arg>/session</Arg>
        <Arg>com.mortbay.Servlet.SessionDump</Arg>
      </Init>
    </Handler>
    <Handler class="com.mortbay.HTTP.Handler.FileHandler"/>
    <Handler class="com.mortbay.HTTP.Handler.NotFoundHandler"/>
  </Context>

  <Context>
    <Path>/servlet/*</Path>
    <ClassPath>./servlets/</ClassPath>
    <Handler class="com.mortbay.HTTP.Handler.Servlet.DynamicHandler"/>
    <Handler class="com.mortbay.HTTP.Handler.NotFoundHandler"/>
  </Context>

  <Context>
    <Path>/javadoc/*</Path>
    <ResourceBase>./javadoc/</ResourceBase>
    <Handler class="com.mortbay.HTTP.Handler.FileHandler"/>
    <Handler class="com.mortbay.HTTP.Handler.NotFoundHandler"/>
  </Context>

</Server>
