=== isabella232/sourceforge-archive/Jetty/src/com/mortbay/Util/configure.dtd
<?xml version="1.0" encoding="ISO8859_1"?>

<!ENTITY % CONFIG "Set|Put|Call">
<!ENTITY % TYPE "String|int|long|boolean|URL|InetAddress|InetAddrPort">
<!ENTITY % VALUE "#PCDATA|Call|New|SystemProperty">
<!ENTITY % TYPEATTR "type (%TYPE;) #IMPLIED " >
<!ENTITY % CLASSATTR "class NMTOKEN #REQUIRED" >
<!ENTITY % NAMEATTR "name NMTOKEN #REQUIRED" >

<!ELEMENT Configure (%CONFIG;)* >
<!ATTLIST Configure %CLASSATTR; >

<!ELEMENT New (Arg*,(%CONFIG;)*)>
<!ATTLIST New %CLASSATTR; >

<!ELEMENT Set ( %VALUE; )* >
<!ATTLIST Set %NAMEATTR; %TYPEATTR; >

<!ELEMENT Put ( %VALUE; )* >
<!ATTLIST Put %NAMEATTR; %TYPEATTR;>

<!ELEMENT Call (Arg*,(%CONFIG;)*)>
<!ATTLIST Call %NAMEATTR;>

<!ELEMENT Arg ( %VALUE; )* >
<!ATTLIST Arg %TYPEATTR; >

<!ELEMENT Value ( #PCDATA | SystemProperty  )* >

<!ELEMENT SystemProperty EMPTY>
<!ATTLIST SystemProperty %NAMEATTR; default NMTOKEN #IMPLIED>

=== isabella232/sourceforge-archive/Jetty/contrib/com/mortbay/Servlets/PackageIndex/JettyServer.xml
<?xml version="1.0"  encoding="ISO-8859-1"?> 
<!DOCTYPE Configure SYSTEM "configure.dtd"> 

<Configure class="com.mortbay.HTTP.HttpServer">
  <Call name="addListener">
    <Arg>
      <New class="com.mortbay.HTTP.SocketListener">
        <Set name="Port">8081</Set>
        <Set name="MinThreads">5</Set>
        <Set name="MaxThreads">255</Set>
        <Set name="MaxIdleTimeMs">50000</Set>
      </New>
    </Arg>
  </Call>

  <Call name="addContext">
    <Arg>/usr/local/pkgs/java</Arg>
    <Set name="ResourceBase">/usr/local/pkgs/java</Set>
    <Set name="ServingResources">TRUE</Set>
  </Call>
  <Call name="addContext">
    <Arg>/usr/local/pkgs/jdk</Arg>
    <Set name="ResourceBase">/usr/local/pkgs/jdk</Set>
    <Set name="ServingResources">TRUE</Set>
  </Call>
  <Call name="addContext">
    <Arg>/</Arg>
    <Call name="addServlet">
      <Arg>PackageIndex</Arg>
      <Arg>/</Arg>
      <Arg>com.mortbay.Servlets.PackageIndex.PackageIndex</Arg>
      <Call name="setInitParameter">
        <Arg>PackageProperties</Arg>
        <Arg>com.mortbay.Servlets.PackageIndex.PackageIndex</Arg>
      </Call>
    </Call>
    <Call name="addHandler">
      <Arg><New class="com.mortbay.HTTP.Handler.NotFoundHandler"/></Arg>
    </Call>
  </Call>

</Configure>

=== isabella232/sourceforge-archive/JettyExtra/tools/src/org/mortbay/servlets/packageindex/JettyServer.xml
<?xml version="1.0"  encoding="ISO-8859-1"?> 
<!DOCTYPE Configure SYSTEM "configure.dtd"> 

<Configure class="org.mortbay.http.HttpServer">
  <Call name="addListener">
    <Arg>
      <New class="org.mortbay.http.SocketListener">
        <Set name="Port">8081</Set>
        <Set name="MinThreads">5</Set>
        <Set name="MaxThreads">255</Set>
        <Set name="MaxIdleTimeMs">50000</Set>
      </New>
    </Arg>
  </Call>

  <Call name="addContext">
    <Arg>/usr/local/pkgs/java</Arg>
    <Set name="ResourceBase">/usr/local/pkgs/java</Set>
    <Set name="ServingResources">TRUE</Set>
  </Call>
  <Call name="addContext">
    <Arg>/usr/local/pkgs/jdk</Arg>
    <Set name="ResourceBase">/usr/local/pkgs/jdk</Set>
    <Set name="ServingResources">TRUE</Set>
  </Call>
  <Call name="addContext">
    <Arg>/</Arg>
    <Call name="addServlet">
      <Arg>PackageIndex</Arg>
      <Arg>/</Arg>
      <Arg>org.mortbay.servlets.packageindex.PackageIndex</Arg>
      <Call name="setInitParameter">
        <Arg>PackageProperties</Arg>
        <Arg>org.mortbay.servlets.packageindex.PackageIndex</Arg>
      </Call>
    </Call>
    <Call name="addHandler">
      <Arg><New class="org.mortbay.http.handler.NotFoundHandler"/></Arg>
    </Call>
  </Call>

</Configure>
